### ISSUE TITLE
Conflict with the vendor directory

### ISSUE THREAD

**Issue by kanlukasz** [pwarchol/vscode-php-file-link#2]
Hej,

Wychwyciłem taki problem, że wtyczka nie działa w momencie gdy w moim projekcie mam katalog vendor.

Log z konsoli wygląda tak:
```
 ERR EACCES: permission denied, stat 'c:\Users\userName\Desktop\vscode-copy\app\public_html\vendor\bin\php-parse': Error: EACCES: permission denied, stat 'c:\Users\userName\Desktop\vscode-copy\app\public_html\vendor\bin\php-parse'
	at statSync (fs.js:1086:3)
	at Object.e.statSync (electron/js2c/asar_bundle.js:5:4315)
	at c:\Users\userName\Desktop\vscode-copy\data\extensions\pwarchol.vscode-php-file-link-0.2.8\out\FileSystemHelper.js:57:20
	at Array.forEach (<anonymous>)
	at Function.findFilesRecursiveSync (c:\Users\userName\Desktop\vscode-copy\data\extensions\pwarchol.vscode-php-file-link-0.2.8\out\FileSystemHelper.js:56:15)
	at c:\Users\userName\Desktop\vscode-copy\data\extensions\pwarchol.vscode-php-file-link-0.2.8\out\FileSystemHelper.js:59:35
	at Array.forEach (<anonymous>)
	at Function.findFilesRecursiveSync (c:\Users\userName\Desktop\vscode-copy\data\extensions\pwarchol.vscode-php-file-link-0.2.8\out\FileSystemHelper.js:56:15)
	at c:\Users\userName\Desktop\vscode-copy\data\extensions\pwarchol.vscode-php-file-link-0.2.8\out\FileSystemHelper.js:59:35
	at Array.forEach (<anonymous>)
	at Function.findFilesRecursiveSync (c:\Users\userName\Desktop\vscode-copy\data\extensions\pwarchol.vscode-php-file-link-0.2.8\out\FileSystemHelper.js:56:15)
	at LinkProvider.<anonymous> (c:\Users\userName\Desktop\vscode-copy\data\extensions\pwarchol.vscode-php-file-link-0.2.8\out\LinkProvider.js:38:74)
	at Generator.next (<anonymous>)
	at c:\Users\userName\Desktop\vscode-copy\data\extensions\pwarchol.vscode-php-file-link-0.2.8\out\LinkProvider.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (c:\Users\userName\Desktop\vscode-copy\data\extensions\pwarchol.vscode-php-file-link-0.2.8\out\LinkProvider.js:4:12)
	at LinkProvider.provideDocumentLinks (c:\Users\userName\Desktop\vscode-copy\data\extensions\pwarchol.vscode-php-file-link-0.2.8\out\LinkProvider.js:24:16)
	at c:\Users\userName\Desktop\vscode-copy\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:175547
	at c:\Users\userName\Desktop\vscode-copy\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:12043
	at new Promise (<anonymous>)
	at m (c:\Users\userName\Desktop\vscode-copy\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:12015)
	at B.provideLinks (c:\Users\userName\Desktop\vscode-copy\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:175527)
	at c:\Users\userName\Desktop\vscode-copy\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:192184
	at Ce._withAdapter (c:\Users\userName\Desktop\vscode-copy\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:180570)
	at Ce.$provideDocumentLinks (c:\Users\userName\Desktop\vscode-copy\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:192160)
	at l._doInvokeHandler (c:\Users\userName\Desktop\vscode-copy\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:12836)
	at l._invokeHandler (c:\Users\userName\Desktop\vscode-copy\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:12520)
	at l._receiveRequest (c:\Users\userName\Desktop\vscode-copy\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:11136)
	at l._receiveOneMessage (c:\Users\userName\Desktop\vscode-copy\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:9973)
	at c:\Users\userName\Desktop\vscode-copy\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:8074
	at fire (c:\Users\userName\Desktop\vscode-copy\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)
	at S.fire (c:\Users\userName\Desktop\vscode-copy\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15497)
	at c:\Users\userName\Desktop\vscode-copy\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:106:29764
	at fire (c:\Users\userName\Desktop\vscode-copy\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)
	at S.fire (c:\Users\userName\Desktop\vscode-copy\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15497)
	at t._receiveMessage (c:\Users\userName\Desktop\vscode-copy\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:20755)
	at c:\Users\userName\Desktop\vscode-copy\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:17641
	at fire (c:\Users\userName\Desktop\vscode-copy\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)
	at acceptChunk (c:\Users\userName\Desktop\vscode-copy\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12862)
	at c:\Users\userName\Desktop\vscode-copy\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12210
	at Socket.v (c:\Users\userName\Desktop\vscode-copy\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:106:13195)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

#### Testowałem to na:
- wirtualce z WSL2
- wersji portable bezpośrednio na Windows

Tu i tu, nie działa

#### Wersja VSCode:
```
Version: 1.56.0
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:09:06.405Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by pwarchol** [comment]
@kanlukasz v0.3.0 opublikowana, daj znać teraz powinno być ok.

**Comment by kanlukasz** [comment]
to również ok 👍
